CREATE TABLE Staff_Info(
StaffID VARCHAR(10) NOT NULL PRIMARY KEY,
StaffName VARCHAR(20) NOT NULL,
Passwd VARCHAR(30) NOT NULL,
Department VARCHAR(20) NOT NULL,
Team VARCHAR(20) NOT NULL,
Duties VARCHAR(20) NOT NULL,
Ranks TINYINT(1) UNSIGNED NOT NULL,
IfAdmin TINYINT(1) UNSIGNED NOT NULL
);

CREATE TABLE Test_Info(
TestID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
TestName VARCHAR(20) NOT NULL
);

CREATE TABLE Item_Poll(
TestID INT UNSIGNED NOT NULL,
QuestionID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
TYPES TINYINT(1) UNSIGNED NOT NULL,
Question VARCHAR(100) NOT NULL,
ChoiceA VARCHAR(50) NOT NULL,
ChoiceB VARCHAR(50) NOT NULL,
ChoiceC VARCHAR(50),
ChoiceD VARCHAR(50),
ChoiceE VARCHAR(50),
ChoiceF VARCHAR(50),
Answer VARCHAR(50) NOT NULL,
Weights INT UNSIGNED NOT NULL,
Checked VARCHAR(20) NOT NULL,
FOREIGN KEY(TestID) REFERENCES Test_Info(TestID)
);

CREATE TABLE History_Score(
StaffID INT UNSIGNED NOT NULL,
TestName VARCHAR(20) NOT NULL,
Score INT UNSIGNED NOT NULL,
FOREIGN KEY(StaffID) REFERENCES Staff_Info(StaffID)
);

INSERT staff_info VALUES
	("0486", "Nanchen Li", "12345", "DCG", "FED", "Coding", 1, 0),
	("0487", "Chengxi Li", "23456", "CDG", "AMS", "NLP", 1, 0),
	("0510", "Weixuan Liu", "34567", "HR", "BP", "Employ", 1, 0)
	;

INSERT Test_Info VALUES (0, "云计算基础"), (0, "数据结构");
	
INSERT history_score VALUE (1, '云计算基础', 80);
INSERT history_score VALUE (1, '数据结构', 100);